services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: blogapi-api:1.0
    expose:
      - "8000"
    entrypoint: ./entrypoint-api.sh
    env_file: .env.prod
    volumes:
      - staticfiles:/staticfiles
    depends_on:
      - postgres-db

  redis:
    image: redis:7.2.4-alpine
    command: redis-server
    expose:
      - "6379"

  postgres-db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.prod
    expose:
      - "5432"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file: .env.prod
    volumes:
      - staticfiles:/staticfiles
      - certbot_certs:/etc/letsencrypt
      - certbot_web:/var/www/certbot
    depends_on:
      - api

  certbot:
    build:
      context: ./certbot
      dockerfile: Dockerfile
    command: echo "Skipping certbot..."
    env_file: .env.prod
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_web:/var/www/certbot
    depends_on:
      - nginx

volumes:
  staticfiles:
  postgres_data:
  certbot_certs:
  certbot_web:
