services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: blogapi-api:1.0
    expose:
      - "8000"
    entrypoint: ./entrypoint-api.sh
    env_file: .env.dev
    volumes:
      - staticfiles:/staticfiles
    depends_on:
      - postgres-db

  redis:
    image: redis:7.2.4-alpine
    command: redis-server
    expose:
      - "6379"

  postgres-db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.dev
    expose:
      - "5432"

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - staticfiles:/staticfiles
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  staticfiles:
  postgres_data:
