version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-api:1.0
    expose:
      - "8000"
    entrypoint: ./entrypoint-api.sh
    env_file: .env.dev
    volumes:
      - staticfiles:/staticfiles
    depends_on:
      - postgres-db

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-celery:1.0
    entrypoint: ./entrypoint-celery.sh
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    env_file: .env.dev
    depends_on:
      - api
      - redis

  redis:
    image: redis:7.2.4-alpine
    command: redis-server
    expose:
      - "6379"

  postgres-db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.dev
    expose:
      - "5432"

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - staticfiles:/staticfiles
      - frontend_build:/var/www/frontend
      - ./nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/frontend/build

volumes:
  staticfiles:
  frontend_build:
  postgres_data:
