version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-api:1.0
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - staticfiles:/staticfiles
    depends_on:
      - postgres-db

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-celery:1.0
    command: celery -A myproject worker -l INFO
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - api
      - redis

  redis:
    image: redis:7.2.4-alpine
    command: redis-server
    ports:
      - "6379:6379"

  postgres-db:
    image: postgres:15
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - staticfiles:/staticfiles
    depends_on:
      - api

volumes:
  staticfiles: #   postgres_data:
