version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-api:1.0
    expose:
      - "8000"
    entrypoint: ./entrypoint-api.sh
    env_file:
      - .env.dev
    volumes:
      - staticfiles:/staticfiles
    depends_on:
      - postgres-db

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-celery:1.0
    entrypoint: ./entrypoint-celery.sh
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    env_file:
      - .env.dev
    depends_on:
      - api
      - redis

  redis:
    image: redis:7.2.4-alpine
    command: redis-server
    expose:
      - "6379"

  postgres-db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.prod.db
    expose:
      - "5432"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - staticfiles:/staticfiles
    depends_on:
      - api

volumes:
  staticfiles:
  postgres_data:
