version: "3"

services:
  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - postgres-db
  
  celery:
    build: .
    command: celery -A myproject worker -l INFO
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    env_file:
      - ../.env
    depends_on:
      - api
      - redis
    
  redis:
    image: redis:7.2.4-alpine
    command: redis-server
  
  postgres-db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
