# Generated by Django 5.0 on 2024-01-22 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_userprofile_is_email_verified_verificationtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationtoken",
            name="send_attempts",
        ),
        migrations.CreateModel(
            name="VerificationEmailUpdateToken",
            fields=[
                (
                    "verificationtoken_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="account.verificationtoken",
                    ),
                ),
                (
                    "new_email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="new email address"
                    ),
                ),
            ],
            bases=("account.verificationtoken",),
        ),
        migrations.CreateModel(
            name="VerificationResetPasswordToken",
            fields=[
                (
                    "verificationtoken_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="account.verificationtoken",
                    ),
                ),
                (
                    "new_password",
                    models.CharField(max_length=128, verbose_name="password"),
                ),
            ],
            bases=("account.verificationtoken",),
        ),
        migrations.CreateModel(
            name="VerificationEmailToken",
            fields=[
                (
                    "verificationtoken_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="account.verificationtoken",
                    ),
                ),
                ("send_attempts", models.IntegerField(default=0)),
            ],
            bases=("account.verificationtoken",),
        ),
    ]
