# Generated by Django 5.0 on 2024-01-28 03:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "account",
            "0004_verificationemailtoken_verificationemailupdatetoken_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationemailtoken",
            name="key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="verificationemailupdatetoken",
            name="key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="verificationresetpasswordtoken",
            name="key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
