# Generated by Django 5.0 on 2024-02-03 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0005_alter_verificationemailtoken_key_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="VerificationResetPasswordToken",
            new_name="VerificationPasswordResetToken",
        ),
    ]
